vich_uploader:
    db_driver: orm

    mappings:
        slider_image:
            uri_prefix: assets/img/slider
            upload_destination: '%kernel.project_dir%/public/assets/img/slider'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
