<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNL5FJiX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNL5FJiX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNL5FJiX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNL5FJiX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNL5FJiX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NL5FJiX',
    'container.build_id' => '9a4303b5',
    'container.build_time' => 1569447678,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNL5FJiX');
