<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWhELDEp\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWhELDEp/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWhELDEp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWhELDEp\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWhELDEp\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WhELDEp',
    'container.build_id' => '21484d1f',
    'container.build_time' => 1569530125,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWhELDEp');
